/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as TaxonomyRouteImport } from './../routes/taxonomy'
import { Route as ReviewRouteImport } from './../routes/review'
import { Route as ComparisonRouteImport } from './../routes/comparison'
import { Route as ClassificationsRouteImport } from './../routes/classifications'
import { Route as AnalyticsRouteImport } from './../routes/analytics'
import { Route as IndexRouteImport } from './../routes/index'

const TaxonomyRoute = TaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificationsRoute = ClassificationsRouteImport.update({
  id: '/classifications',
  path: '/classifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/classifications': typeof ClassificationsRoute
  '/comparison': typeof ComparisonRoute
  '/review': typeof ReviewRoute
  '/taxonomy': typeof TaxonomyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/classifications': typeof ClassificationsRoute
  '/comparison': typeof ComparisonRoute
  '/review': typeof ReviewRoute
  '/taxonomy': typeof TaxonomyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/classifications': typeof ClassificationsRoute
  '/comparison': typeof ComparisonRoute
  '/review': typeof ReviewRoute
  '/taxonomy': typeof TaxonomyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/classifications'
    | '/comparison'
    | '/review'
    | '/taxonomy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/classifications'
    | '/comparison'
    | '/review'
    | '/taxonomy'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/classifications'
    | '/comparison'
    | '/review'
    | '/taxonomy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ClassificationsRoute: typeof ClassificationsRoute
  ComparisonRoute: typeof ComparisonRoute
  ReviewRoute: typeof ReviewRoute
  TaxonomyRoute: typeof TaxonomyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taxonomy': {
      id: '/taxonomy'
      path: '/taxonomy'
      fullPath: '/taxonomy'
      preLoaderRoute: typeof TaxonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifications': {
      id: '/classifications'
      path: '/classifications'
      fullPath: '/classifications'
      preLoaderRoute: typeof ClassificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ClassificationsRoute: ClassificationsRoute,
  ComparisonRoute: ComparisonRoute,
  ReviewRoute: ReviewRoute,
  TaxonomyRoute: TaxonomyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
